<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.XYZcompany.ecommerce.testscripts.SuiteFile" tests="1" time="0.000" ignored="0" failures="0" timestamp="21 Jan 2017 13:40:24 GMT" skipped="0" hostname="DESKTOP-MQ4CHD1" errors="1">
  <testcase name="reporting" time="0.000" classname="com.XYZcompany.ecommerce.testscripts.SuiteFile">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.XYZcompany.ecommerce.logs.ExtentReportsLogs.opentheReport(ExtentReportsLogs.java:45)
	at com.XYZcompany.ecommerce.testscripts.SuiteFile.reporting(SuiteFile.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:357)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- reporting -->
</testsuite> <!-- com.XYZcompany.ecommerce.testscripts.SuiteFile -->
